#most frequent pattern of a certain length

seq = "AATCGTTAAATCGTTAACCTGCAAGAGGAAAGACCTGCATTGATTCAATCGTTAAGAGGAAAGCCATTGGAACCTGCAAATCGTTAAGAGGAAAGCCATTGGACCATTGGAACCTGCATTGATTCAATCGTTAAATCGTTATTGATTCAATCGTTATTGATTCAATCGTTAACCTGCACCATTGGAACCTGCACCATTGGACCATTGGATTGATTCCCATTGGAAATCGTTAAATCGTTATTGATTCAATCGTTATTGATTCAGAGGAAAGCCATTGGAAGAGGAAAGTTGATTCCCATTGGAAGAGGAAAGCCATTGGAAATCGTTATTGATTCAGAGGAAAGAGAGGAAAGTTGATTCCCATTGGAACCTGCACCATTGGATTGATTCAGAGGAAAGTTGATTCCCATTGGACCATTGGAAATCGTTATTGATTCCCATTGGAAATCGTTATTGATTCTTGATTCACCTGCAAGAGGAAAGTTGATTCTTGATTCAATCGTTAAATCGTTATTGATTCAGAGGAAAGTTGATTCTTGATTCAATCGTTACCATTGGAAATCGTTAAATCGTTACCATTGGAAGAGGAAAGCCATTGGACCATTGGATTGATTCAGAGGAAAGTTGATTCAGAGGAAAGTTGATTCAATCGTTAAATCGTTACCATTGGAAGAGGAAAGAATCGTTATTGATTCAATCGTTAACCTGCAACCTGCATTGATTCAATCGTTAAATCGTTAAGAGGAAAGAGAGGAAAGAGAGGAAAGACCTGCAAATCGTTAAATCGTTATTGATTCCCATTGGAAGAGGAAAGTTGATTCTTGATTCTTGATTCAATCGTTACCATTGGA"
length = 13


def patternFreq(seq, length):
	pattern = {}	
	i=0
	while i<(len(seq)-(length-1)):
		p = seq[i:i+length]
		if p in pattern:
			pattern[p] = pattern[p]+1
		else:
			pattern[p] = 1
		i = i+1

	s = list(pattern.values())
	ma = max(s)
	for key, value in pattern.items():
		if ma == value:
			print (key)

	return

patternFreq(seq, length)